set(_CATKIN_CURRENT_PACKAGE "my_serial_node")
set(my_serial_node_VERSION "0.0.0")
set(my_serial_node_MAINTAINER "xs <xs@todo.todo>")
set(my_serial_node_PACKAGE_FORMAT "1")
set(my_serial_node_BUILD_DEPENDS "serial" "std_msgs")
set(my_serial_node_BUILD_EXPORT_DEPENDS "serial" "std_msgs")
set(my_serial_node_BUILDTOOL_DEPENDS "catkin")
set(my_serial_node_BUILDTOOL_EXPORT_DEPENDS )
set(my_serial_node_EXEC_DEPENDS "serial" "std_msgs")
set(my_serial_node_RUN_DEPENDS "serial" "std_msgs")
set(my_serial_node_TEST_DEPENDS )
set(my_serial_node_DOC_DEPENDS )
set(my_serial_node_DEPRECATED "")